#!/usr/bin/env python
"""Regenerate the regime-sensitive charts for every gauge, on both regime definitions.

For each measure (CPI supercore, core PCE, market-based core PCE) this writes:
  - the MAIN result (hard v/u=1 threshold) to the measure-folder top level, and
  - the ROBUSTNESS cross-check (logistic, mean-centred) to a robustness_logistic/ subfolder,
each comprising the state-dependent IRF chart (+ _data.csv), the nine-spec robustness panel
(fig3) + robustness_grid.csv, the drop-2021-22 two-paradigms chart (fig11) + two_paradigms_data.csv,
and the point-IRF / linear-baseline CSVs.

The regime-independent / cross-measure figures (continuous-interaction passthrough curve fig4,
market-price ladder fig9, paradigm map fig10, and the CPI component attribution fig2/2b) are
generated by analysis.ipynb, not here.

Reuses the canonical estimators in svar_lp_utils.py; rebuilds the panel from data_cache so the
script is reproducible without the notebook. Run:  python regime_comparison.py
"""
from __future__ import annotations
import warnings; warnings.filterwarnings("ignore")
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))                 # local svar_lp_utils + vendored shared/
import svar_lp_utils as u
from shared import chart_style as cs

CACHE = HERE / "data_cache"
HORIZONS = list(range(0, 25))
N_LAGS = 6
GAMMA = 1.5

cs.use()
HOT, SLACK, LIN = cs.ACCENT, cs.PRIMARY, cs.MUTE2      # tight / slack / linear-no-state
SRC = "Sources: Kanzig (2021); Barnichon (2019); FRED; BLS; BEA. Joshua Bailey"


def _pfmt(p):
    """p-value label: avoid a misleading '0.00' for very small p."""
    return "<0.01" if p < 0.005 else f"{p:.2f}"


def _yticks(*arrays, n=4):
    """Sparse, honest y ticks tight to the plotted arrays (straddling 0, minimal overshoot)."""
    vals = np.concatenate([np.asarray(a, float).ravel() for a in arrays])
    lo, hi = min(np.nanmin(vals), 0.0), max(np.nanmax(vals), 0.0)
    rng = (hi - lo) or 1.0
    ticks = MaxNLocator(n).tick_values(lo, hi)
    ticks = ticks[(ticks >= lo - 0.12 * rng) & (ticks <= hi + 0.18 * rng)]
    if 0.0 not in ticks:
        ticks = np.sort(np.append(ticks, 0.0))
    return ticks


# ---------------------------------------------------------------------------
# Data: replicate the notebook Data cell + add the PCE dependents
# ---------------------------------------------------------------------------
def build_df() -> pd.DataFrame:
    cpi = pd.read_csv(CACHE / "cpi_components.csv", index_col=0, parse_dates=True)
    shock = pd.read_csv(CACHE / "kanzig_oil_supply_shock.csv", parse_dates=["date"]).set_index("date")
    shock_pre = pd.read_csv(CACHE / "kanzig_oil_supply_shock_precovid.csv", parse_dates=["date"]).set_index("date")
    macro = pd.read_csv(CACHE / "fred_macro.csv", index_col=0, parse_dates=True)

    idx = pd.date_range("1975-01-01", "2026-04-01", freq="MS")
    df = pd.DataFrame(index=idx)
    COMPONENTS = {"Supercore (total)": "pcuserh", "Airfares": "itua",
                  "Transportation services": "pcucst", "Lodging away from home": "pcuhsro",
                  "Medical-care services": "pcums", "Recreation services": "iers",
                  "Education & comms": "idecs"}
    for lbl, c in COMPONENTS.items():
        df["ln_" + c] = np.log(cpi[c].reindex(idx).interpolate(limit_area="inside")) * 100
    df["shock"] = shock["shock"].reindex(idx)
    df["shock_pre"] = shock_pre["shock"].reindex(idx)
    df["surprise"] = shock["surprise"].reindex(idx)
    # long v/u (Barnichon HWI rescaled to JOLTS units via 2001+ no-intercept fit)
    _bev = pd.read_csv(CACHE / "beveridge_barnichon.csv")
    _bev.columns = ["date", "unemp", "lf", "vac"]
    _bev = _bev.set_index(pd.to_datetime(_bev["date"]))
    _vu_long = (_bev["vac"] / _bev["unemp"]).reindex(idx)
    df["vu_jolts"] = (macro["job_openings"] / macro["unemployed"]).reindex(idx)
    _ov = pd.concat([_vu_long.rename("L"), df["vu_jolts"].rename("J")], axis=1).dropna()
    _scale = (_ov.L * _ov.J).sum() / (_ov.L ** 2).sum()
    df["vu"] = _vu_long * _scale
    df["ugap_tight"] = -(macro["unrate"] - macro["nrou_cbo"].reindex(idx).ffill())
    df["wage_raw"] = macro["atl_wage"].reindex(idx)
    df["wage_cyc"] = df["wage_raw"] - df["wage_raw"].rolling(60, min_periods=36).mean().shift(1)
    df["ln_wti"] = (np.log(macro["wti"]) * 100).reindex(idx)
    df["exp5"] = macro["exp5yr"].reindex(idx)
    df["exp10"] = macro["exp10yr"].reindex(idx)
    df["exp_dev"] = df["exp5"] - df["exp10"]
    _shap = pd.read_csv(CACHE / "shapiro_supply_demand_pce.csv", parse_dates=["date"]).set_index("date")
    df["shapiro_demand"] = _shap["demand_yoy"].reindex(idx)
    # PCE dependents (not in the base CPI cell)
    _pce = pd.read_csv(CACHE / "pce_core.csv", parse_dates=["date"]).set_index("date")
    df["ln_pce_core"] = (np.log(_pce["jcxfebm"]) * 100).reindex(idx)
    df["ln_pce_super"] = (np.log(_pce["jcsxehm"]) * 100).reindex(idx)
    _mb = pd.read_csv(CACHE / "market_based_core_pce.csv", parse_dates=["date"]).set_index("date")["mb_core_pce"]
    df["ln_mb_corepce"] = (np.log(_mb) * 100).reindex(idx)
    return df


# ---------------------------------------------------------------------------
# Plot helpers (ported from analysis.ipynb, parameterised by the regime weight F)
# ---------------------------------------------------------------------------
def plot_state_irf(sd_df, lin_df, title_insight, title_desc, regime_tag, note, out_path):
    """Two-regime cumulative IRF in the house style: floated y-axis, direct end
    labels, 60% HAC bands, an annotated 24m hot-slack gap."""
    Z = 0.8416   # 60% band (two-sided normal), matching the note's headline chart
    s = sd_df.set_index("h"); l = lin_df.set_index("h")
    h = s.index.to_numpy()
    fig, ax = cs.figure(7.8, 6.1, rect=(0.055, 0.27, 0.80, 0.51))
    for beta, se, col in [(s.betaH, s.seH, HOT), (s.betaL, s.seL, SLACK)]:
        ax.fill_between(h, beta - Z * se, beta + Z * se, color=col, alpha=0.12, lw=0)
        ax.plot(h, beta, color=col, lw=2.3)
    ax.plot(l.index, l.beta, color=LIN, lw=1.5, ls=":")
    ax.axhline(0, color=cs.BASE, lw=0.8)
    ax.set_xlim(0, 26); ax.set_xticks([0, 6, 12, 18, 24])
    ax.set_xlabel("Months after the shock")
    ticks = _yticks(s.betaH - Z * s.seH, s.betaL - Z * s.seL,
                    s.betaH + Z * s.seH, s.betaL + Z * s.seL)
    cs.floated_yaxis(ax, ticks)
    ax.set_ylim(ticks.min(), ticks.max())      # tight to the data, no dead space up top
    # direct end-of-line labels (regime-aware; nudged apart so they never overlap)
    hard = "v/u = 1" in regime_tag
    tight_lab = "Tight (v/u ≥ 1)" if hard else "Tight labour market"
    slack_lab = "Slack (v/u < 1)" if hard else "Slack labour market"
    ends = [(tight_lab, s.betaH.iloc[-1], HOT),
            (slack_lab, s.betaL.iloc[-1], SLACK),
            ("Unconditional", l.beta.iloc[-1], LIN)]
    yy = cs.spread([e[1] for e in ends], 0.13 * (ax.get_ylim()[1] - ax.get_ylim()[0]))
    for (lab, _, col), y in zip(ends, yy):
        cs.direct_label(ax, 24.4, y, lab, col, size=8.5, bold=(col is not LIN))
    # gap stat, tucked into the empty upper-left (clear of the floated labels and the data)
    g12, p12 = s.loc[12, "diff"], s.loc[12, "wald_p"]
    g24, p24 = s.loc[24, "diff"], s.loc[24, "wald_p"]
    ax.text(0.13, 0.97, "Tight − slack gap\n"
            f"{g12:+.2f}pp at 12m (p={_pfmt(p12)})\n{g24:+.2f}pp at 24m (p={_pfmt(p24)})",
            transform=ax.transAxes, ha="left", va="top", ma="left", fontsize=7.8,
            family=cs.SANS, color=cs.INK, linespacing=1.4, zorder=8,
            bbox=dict(boxstyle="round,pad=0.5", facecolor="#F3EDE3", edgecolor="none", alpha=0.94))
    cs.title(fig, title_insight, title_desc)
    cs.source(fig, note + "\n" + SRC)
    cs.check_overlaps(fig, Path(out_path).name)
    z60, z90 = 0.8416, 1.645  # two-sided normal critical values
    chart_data = pd.DataFrame({
        "months_after_shock": s.index, "hot": s.betaH.values, "slack": s.betaL.values,
        "linear_no_state": l["beta"].reindex(s.index).values,
        "hot_lower60": (s.betaH - z60 * s.seH).values, "hot_upper60": (s.betaH + z60 * s.seH).values,
        "slack_lower60": (s.betaL - z60 * s.seL).values, "slack_upper60": (s.betaL + z60 * s.seL).values,
        "hot_lower90": (s.betaH - z90 * s.seH).values, "hot_upper90": (s.betaH + z90 * s.seH).values,
        "slack_lower90": (s.betaL - z90 * s.seL).values, "slack_upper90": (s.betaL + z90 * s.seL).values})
    chart_data.to_csv(out_path.replace(".png", "_data.csv"), index=False)
    fig.savefig(out_path); plt.close(fig)


def run_robustness(y, start, specs, h=24):
    rows = []
    for lbl, dd, F, sr, nl in specs:
        s = u.state_sign_lp(dd.loc[start:], y, "shock", F, [h], state_raw=sr, n_lags=nl).iloc[0]
        rows.append({"spec": lbl, "diff": s["diff"], "wald_p": s["wald_p"]})
    return pd.DataFrame(rows).set_index("spec")


def plot_robustness(rob, measure, sample_lbl, regime_tag, out_path, peak_note=""):
    """Signed horizontal bars: hot-slack gap across tightness measures and sample cuts,
    accent where significant at 10% (HAC Wald), muted otherwise."""
    r = rob.iloc[::-1]; yv = np.arange(len(r))
    fig, ax = cs.figure(7.8, 6.2, rect=(0.30, 0.22, 0.66, 0.52))
    ax.barh(yv, r["diff"], color=[cs.ACCENT if p < 0.1 else cs.MUTE for p in r.wald_p])
    ax.axvline(0, color=cs.BASE, lw=0.8)
    ax.set_yticks(yv); ax.set_yticklabels(r.index, fontsize=9)
    ax.spines["left"].set_visible(False); ax.tick_params(length=0)
    lo = min(r["diff"].min() - 0.12, -0.12); hi = r["diff"].max() + max(0.5, r["diff"].max() * 0.28)
    ax.set_xlim(lo, hi)
    for yy, dv, p in zip(yv, r["diff"], r.wald_p):
        # always place the p-label just right of zero (or the bar tip), left-aligned, so a
        # negative bar's label never runs left across the axis into the category tick labels
        ax.text(max(dv, 0.0) + 0.03, yy, f"p={_pfmt(p)}", va="center",
                ha="left", fontsize=7.5, color=cs.SUBTLE, family=cs.SANS)
    ax.set_xlabel("Hot minus slack response, pp (per +1 s.d. shock, at 24 months)")
    note = ("Note. Accent bars mark a hot-vs-slack difference significant at 10%% (HAC Wald). Sample %s.%s"
            % (sample_lbl, (" " + peak_note) if peak_note else ""))
    cs.title(fig, "Hot-minus-slack gap across tightness gauges and sample cuts",
             "%s, 24-month gap in pp (%s)" % (measure[:1].upper() + measure[1:], regime_tag))
    cs.source(fig, note + "\n" + SRC)
    cs.check_overlaps(fig, Path(out_path).name)
    fig.savefig(out_path); plt.close(fig)


def two_paradigm_irf(df, df_no2122, y, F, start, measure, regime_tag, out_path):
    sd_full = u.state_sign_lp(df.loc[start:], y, "shock", F, HORIZONS, state_raw="vu", n_lags=N_LAGS)
    sdx = u.state_sign_lp(df_no2122.loc[start:], y, "shock", F, HORIZONS, state_raw="vu", n_lags=N_LAGS)
    f, x = sd_full.set_index("h"), sdx.set_index("h"); h = f.index.to_numpy()
    fig, ax = cs.figure(7.8, 6.3, rect=(0.055, 0.25, 0.90, 0.47))
    ax.fill_between(h, f.betaH - 1.645 * f.seH, f.betaH + 1.645 * f.seH, color=HOT, alpha=0.10, lw=0)
    ax.plot(h, f.betaH, color=HOT, lw=2.4, label="Hot, full sample (2021-22 included)")
    ax.plot(x.index, x.betaH, color=HOT, lw=2.0, ls="--", label="Hot, excluding 2021-22 (clean supply)")
    ax.plot(h, f.betaL, color=SLACK, lw=1.9, label="Slack labour market")
    ax.axhline(0, color=cs.BASE, lw=0.8); ax.set_xlim(0, 24); ax.set_xticks([0, 6, 12, 18, 24])
    ax.set_xlabel("Months after the shock")
    cs.floated_yaxis(ax, _yticks(f.betaH - 1.645 * f.seH, f.betaH + 1.645 * f.seH, f.betaL, x.betaH))
    cs.legend(ax, above=True)
    g24f = f.betaH.iloc[-1] - f.betaL.iloc[-1]; g24x = x.betaH.iloc[-1] - x.betaL.iloc[-1]
    note = ("Note. Cumulative price response to a price-raising oil-supply shock, per +1 s.d. The hot-regime "
            "response on the full sample versus excluding 2021-22 isolates whether the amplification depends on "
            "that episode. 24-month hot-slack gap: full %.2f, excluding 2021-22 %.2f." % (g24f, g24x))
    cs.title(fig, "The hot-regime response, with and without the 2021-22 episode",
             "%s, cumulative price response in %% (%s)" % (measure[:1].upper() + measure[1:], regime_tag))
    cs.source(fig, note + "\n" + SRC)
    cs.check_overlaps(fig, Path(out_path).name)
    fig.savefig(out_path); plt.close(fig)
    out = pd.DataFrame({"h": f.index, "hot_full": f.betaH.values, "hot_ex2122": x.betaH.reindex(f.index).values,
                        "slack": f.betaL.values})
    return out, g24f, g24x


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
MEASURES = [
    dict(folder="cpi_supercore", y="ln_pcuserh", start="1983",
         irf="fig1_supercore_state_dependent", label="CPI supercore", sample="1983-2025", peak="",
         insight="Energy passthrough into CPI supercore rises with labour-market tightness",
         desc="CPI supercore response to a price-raising oil-supply shock, %"),
    dict(folder="pce_core", y="ln_pce_core", start="1975",
         irf="fig1b_core_pce_state_dependent", label="core PCE", sample="1975-2025",
         peak="Note the PCE gauges peak at 12-18m; at 24m the gap is past its peak.",
         insight="The tightness split is muted in the administered-heavy headline core PCE",
         desc="Core PCE response to a price-raising oil-supply shock, %"),
    dict(folder="pce_market_based", y="ln_mb_corepce", start="1987",
         irf="fig1_market_based_state_dependent", label="market-based core PCE", sample="1987-2025",
         peak="Note the PCE gauges peak at 12-18m; at 24m the gap is past its peak.",
         insight="Energy passes into market-priced core inflation only when labour is tight",
         desc="Market-based core PCE response to a price-raising oil-supply shock, %"),
]

REGIME_TAG = {"logistic": "logistic split at the mean", "vu1_hard": "hard cut at v/u = 1"}


def irf_note(sample, method):
    base = ("Note. Cumulative response of the price level to a +1 s.d. Kanzig oil-supply-news shock "
            "(~+10% oil-price rise), price-falling shocks carried as controls; 6 lags, 60% HAC bands. ")
    if method == "logistic":
        reg = ("Tight/slack are the high/low regimes of a logistic transition in the lagged vacancy/"
               "unemployment ratio (Barnichon HWI spliced with JOLTS), centred on its sample mean. ")
    else:
        reg = ("Tight = lagged v/u at or above one vacancy per unemployed worker (v/u >= 1, 'balance'); "
               "slack = below. ")
    return base + reg + ("Monthly local projection, %s." % sample)


def main():
    df = build_df()
    df_no2122 = df.copy(); df_no2122.loc["2021-01-01":"2022-12-01", "shock"] = np.nan
    df_pre = df.copy(); df_pre.loc["2020-01-01":, "shock"] = np.nan

    F_log = u.logistic_transition(df.vu.dropna(), GAMMA).reindex(df.index).shift(1)
    F_thr = u.hard_threshold(df.vu, 1.0).reindex(df.index).shift(1)
    F_jolts = u.logistic_transition(df.vu_jolts.dropna(), GAMMA).reindex(df.index).shift(1)
    F_ug = u.logistic_transition(df.ugap_tight.dropna(), GAMMA).reindex(df.index).shift(1)
    F_wg = u.logistic_transition(df.wage_cyc.dropna(), GAMMA).reindex(df.index).shift(1)
    F_infl = u.logistic_transition(df.exp_dev.dropna(), GAMMA).reindex(df.index).shift(1)
    F_shap = u.logistic_transition(df.shapiro_demand.dropna(), GAMMA).reindex(df.index).shift(1)

    def specs_for(method):
        # "swap v/u baseline only": the four Barnichon-v/u rows use the method's F; alt gauges stay logistic
        Fb = F_thr if method == "vu1_hard" else F_log
        vlab = "v/u >= 1 (hard)" if method == "vu1_hard" else "v/u (Barnichon)"
        return [
            (vlab, df, Fb, "vu", N_LAGS),
            (f"{vlab}, drop 2021-22", df_no2122, Fb, "vu", N_LAGS),
            (f"{vlab}, pre-2020", df_pre, Fb, "vu", N_LAGS),
            (f"{vlab}, n_lags=12", df, Fb, "vu", 12),
            ("v/u JOLTS only, 2001+", df, F_jolts, "vu_jolts", N_LAGS),
            ("u-gap tightness", df, F_ug, "ugap_tight", N_LAGS),
            ("wage cyclical (vs trend)", df, F_wg, "wage_cyc", N_LAGS),
            ("demand-driven (Shapiro)", df, F_shap, "shapiro_demand", N_LAGS),
            ("exp. de-anchoring (5y-10y)", df, F_infl, "exp_dev", N_LAGS),
        ]

    # v/u=1 (hard threshold) is the MAIN result -> written to the measure folder top level;
    # the logistic smooth split is the robustness cross-check -> a robustness_logistic/ subfolder.
    REG_DIR = {"vu1_hard": ".", "logistic": "robustness_logistic"}

    print("=== generating outputs: v/u=1 (main, top level) + logistic (robustness subfolder) ===")
    summary = []
    for m in MEASURES:
        for method, F in [("vu1_hard", F_thr), ("logistic", F_log)]:
            outdir = (HERE / m["folder"] / REG_DIR[method]).resolve()
            outdir.mkdir(parents=True, exist_ok=True)
            tag = REGIME_TAG[method]
            sd = u.state_sign_lp(df.loc[m["start"]:], m["y"], "shock", F, HORIZONS, state_raw="vu", n_lags=N_LAGS)
            lin = u.linear_pos_lp(df.loc[m["start"]:], m["y"], "shock", HORIZONS, state_raw="vu", n_lags=N_LAGS)
            plot_state_irf(sd, lin, m["insight"], m["desc"], tag, irf_note(m["sample"], method),
                           str(outdir / f"{m['irf']}.png"))
            sd.to_csv(outdir / "state_dependent_irf.csv", index=False)
            lin.to_csv(outdir / "linear_irf.csv", index=False)
            rob = run_robustness(m["y"], m["start"], specs_for(method))
            plot_robustness(rob, m["label"], m["sample"], tag, str(outdir / "fig3_robustness.png"), m["peak"])
            rob.to_csv(outdir / "robustness_grid.csv")
            tp, g24f, g24x = two_paradigm_irf(df, df_no2122, m["y"], F, m["start"], m["label"], tag,
                                              str(outdir / "fig11_two_paradigms.png"))
            tp.to_csv(outdir / "two_paradigms_data.csv", index=False)
            g12 = sd.set_index("h").loc[12, ["diff", "wald_p"]]
            g24 = sd.set_index("h").loc[24, ["diff", "wald_p"]]
            sig = (rob.wald_p < 0.1).sum()
            print(f"  {m['folder']:18s} {method:9s}: 12m gap {g12['diff']:+.2f} (p={g12['wald_p']:.3f}) | "
                  f"24m {g24['diff']:+.2f} (p={g24['wald_p']:.3f}) | robust {sig}/9 | "
                  f"2-paradigm 24m full {g24f:+.2f} ex-2122 {g24x:+.2f}")
            summary.append((m["folder"], method, g24["diff"], g24["wald_p"]))
    print("\nDone.")


if __name__ == "__main__":
    main()
